PERCENTILE: [1,99]
NORM: false
CHARGE_KEY: ChargeAveRange
CHARGEDICT: false
PEAK_FINDER: false
CUTTED_WVF: 0
THRESHOLD: 0.1
WIDTH: 15
PROMINENCE: 0.01
ACCURACY: 200
COMPARE: CHANNELS
TERMINAL_MODE: true
SCINT_FIT: true
FIT: norm_gaussian
NAME: DatConfig
