ACCURACY: 150
ALIGN: false
CHARGE_KEY: AnaChargeAveRange
COMPARE: CHANNELS
CUT_THRESHOLD: true
CUTTED_WVF: -1
DENSITY: false
FILTER: true
FILTER_SIGMA: 2
FIT: gaussian
LEGEND: true
LIMITS: false
LOGX: false
LOGY: true
LOGZ: true
MICRO_SEC: true
NAME: VisConfig
NORM: false
PE: true
PEAK_DISTANCE: 30
PEAK_FINDER: false
PERCENTILE:
- 4
- 98
PROMINENCE: 0.03
SCINT_FIT: Quenching
SHOW: true
SHOW_PARAM: true
SHOW_AVE: AveWvf
SHOW_LEGEND: true
SHOW_FIT_PARAMETERS: true
SPACE_OUT: 0
STATS: true
STYLE: CIEMAT
TERMINAL_MODE: true
TERMINAL_OUTPUT: true
THRESHOLD: 0
WFV_FILTER: false
WIDTH: 10
XLIM:
- 2.5e-06
- 1.25e-05
YLIM:
- -2
- 30
ZLIM:
- 0
- 0
