MICRO_SEC: true
NORM: true
LOGX: false
LOGY: false
LOGZ: true
CHARGE_KEY: ChargeAveRange
CHARGEDICT: false
PEAK_FINDER: false
CUTTED_WVF: 0
STATS: false
LEGEND: true
THRESHOLD: 0
WIDTH: 15
PROMINENCE: 0.02
PEAK_DISTANCE: 80
ACCURACY: 250
SHOW_AVE: AveWvf
SHOW_PARAM: true
SHOW: true
COMPARE: CHANNELS
TERMINAL_MODE: true
PRINT_KEYS: false
SCINT_FIT: true
FIT: norm_gaussian
STYLE: HEP_style
NAME: VisConfig
ALIGN: false
PERCENTILE:
- 1
- 99
