MICRO_SEC: true
NORM: false
LOGX: false
LOGY: false
LOGZ: false
CHARGE_KEY: ChargeAveRange
CHARGEDICT: false
PEAK_FINDER: false
CUTTED_WVF: 0
STATS: false
LEGEND: true
THRESHOLD: 0
WIDTH: 10
PROMINENCE: 0.01
PEAK_DISTANCE: 40
ACCURACY: 150
SHOW_AVE: AveWvf
SHOW_PARAM: true
SHOW: true
COMPARE: CHANNELS
TERMINAL_MODE: true
PRINT_KEYS: false
SCINT_FIT: true
FIT: gaussian
STYLE: HEP_style
NAME: VisConfig
ALIGN: false
PERCENTILE:
- 1
- 98
