# UNIT SETTINGS
MICRO_SEC: false
PE: false
# PLOT SETTINGS
NORM: false
DENSITY: false
LOGX: false
LOGY: false
LOGZ: false
# DEFAULT SETTINGS
CHARGE_KEY: ChargeAveRange
PEAK_FINDER: false
CUTTED_WVF: 0
STATS: false
LEGEND: true
THRESHOLD: 0
WIDTH: 20
PROMINENCE: 0.05
PEAK_DISTANCE: 20
ACCURACY: 200
SHOW_PARAM: true
SHOW: true
COMPARE: CHANNELS
TERMINAL_MODE: true
SCINT_FIT: false
FIT: gaussian
STYLE: HEP_style
NAME: VisConfig
ALIGN: true
SPACE_OUT: 10
PERCENTILE:
- 1
- 99
