MICRO_SEC: true
NORM: true
LOGX: false
LOGY: false
LOGZ: false
CHARGE_KEY: ChargeAveRange
CHARGEDICT: false
PEAK_FINDER: false
CUTTED_WVF: 0
STATS: false
LEGEND: true
THRESHOLD: 0
WIDTH: 20
PROMINENCE: 0.01
PEAK_DISTANCE: 20
ACCURACY: 150
SHOW_AVE: AveWvf
SHOW_PARAM: true
SHOW: true
COMPARE: CHANNELS
TERMINAL_MODE: true
PRINT_KEYS: false
SCINT_FIT: true
FIT: megacell_v3
STYLE: HEP_style
NAME: VisConfig
ALIGN: false
PERCENTILE:
- 2
- 99
