MICRO_SEC: false
NORM: false
DENSITY: false
LOGX: false
LOGY: false
LOGZ: false
CHARGE_KEY: ChargeAveRange
CHARGEDICT: false
PEAK_FINDER: false
CUTTED_WVF: 0
STATS: false
LEGEND: false
THRESHOLD: 0
WIDTH: 20
PROMINENCE: 0.01
PEAK_DISTANCE: 20
ACCURACY: 150
SHOW_PARAM: true
SHOW: true
COMPARE: RUNS
TERMINAL_MODE: true
PRINT_KEYS: false
SCINT_FIT: false
FIT: gaussian
STYLE: HEP_style
NAME: VisConfig
ALIGN: false
SPACE_OUT: 0
PERCENTILE:
- 1
- 99