NORM: false
CHARGE_KEY: ChargeAveRange
CHARGEDICT: false
PEAK_FINDER: false
CUTTED_WVF: 0
THRESHOLD: 0.1
WIDTH: 5
PROMINENCE: 0.01
ACCURACY: 75
COMPARE: CHANNELS
TERMINAL_MODE: true
PRINT_KEYS: false
SCINT_FIT: true
FIT: gaussian
NAME: DatConfig
