MICRO_SEC: true
NORM: false
LOGX: false
LOGY: false
LOGZ: true
CHARGE_KEY: ChargeAveRange
CHARGEDICT: false
PEAK_FINDER: false
CUTTED_WVF: 0
LEGEND: true
THRESHOLD: 0
WIDTH: 20
PROMINENCE: 0.01
PEAK_DISTANCE: 100
ACCURACY: 250
SHOW_AVE: AveWvf
SHOW_PARAM: true
SHOW: true
COMPARE: RUNS
TERMINAL_MODE: true
PRINT_KEYS: false
SCINT_FIT: true
FIT: norm_gaussian
STYLE: HEP_style
NAME: VisConfig
ALIGN: false
